
version: 2.1

jobs:
  publish-release:
    docker:
      - image: circleci/node:latest
    steps: 
      - checkout
      - name: Git config
        run: |
          git config user.name "${GITHUB_USER}"
          git config user.email "${GITHUB_EMAIL}"
      - run:
          name: Npm auth
          command: npm config set //registry.npmjs.org/:_authToken $NPM_TOKEN
      - run: npm install
      - run: npm run release
        env:
          GITHUB_TOKEN: ${{ GITHUB_TOKEN }}

workflows:
  version: 2.1
  publish_release:
    jobs:
      - publish-release:
          filters:
            branches:
              only: dev
